import { hashSync } from 'bcrypt';

const figmaSampleData = {
  products: [
    // NEW ARRIVALS - Homepage Section
    {
      name: 'T-SHIRT WITH TAPE DETAILS',
      slug: 't-shirt-with-tape-details',
      category: 'T-Shirts',
      description: 'Classic t-shirt with unique tape details. Made from premium cotton fabric that offers superior comfort and style. Perfect for casual occasions.',
      images: ['/images/product-tshirt-tape.svg', '/images/product-tshirt-tape.svg'],
      price: 12000,
      brand: 'Casual',
      rating: 4.5,
      numReviews: 0,
      stock: 100,
      isFeatured: true,
      banner: null,
      colors: ['White', 'Black', 'Gray'],
      sizes: ['Small', 'Medium', 'Large', 'X-Large'],
      discount: 0,
    },
    {
    name: 'SKINNY FIT JEANS',
    slug: 'skinny-fit-jeans',
    category: 'jeans',
    description: 'Modern skinny fit jeans crafted from premium denim. Features a sleek silhouette and comfortable stretch fabric for all-day wear.',
    images: ['/images/sample-products/p2-1.jpg'],
    price: 24000,
      brand: 'Casual',
      rating: 3.5,
      numReviews: 0,
      stock: 80,
      isFeatured: true,
      banner: null,
      colors: ['Blue', 'Black'],
      sizes: ['Small', 'Medium', 'Large', 'X-Large'],
      discount: 20,
    },
    {
    name: 'CHECKERED SHIRT',
    slug: 'checkered-shirt',
    category: 'shirt',
    description: 'Classic checkered shirt perfect for casual occasions. Made from soft, breathable cotton with a timeless pattern.',
    images: ['/images/sample-products/p3-1.jpg'],
    price: 18000,
      brand: 'Casual',
      rating: 4.5,
      numReviews: 0,
      stock: 90,
      isFeatured: true,
      banner: null,
      colors: ['Red', 'Blue', 'Green'],
      sizes: ['Small', 'Medium', 'Large', 'X-Large'],
      discount: 0,
    },
    {
    name: 'SLEEVE STRIPED T-SHIRT',
    slug: 'sleeve-striped-t-shirt',
    category: 't-shirts',
    description: 'A stylish t-shirt featuring bold horizontal stripes on the sleeves. Perfect for casual outings with a modern athletic look.',
    images: ['/images/sample-products/p4-1.jpg'],
    price: 13000,
      brand: 'Casual',
      rating: 4.5,
      numReviews: 0,
      stock: 120,
      isFeatured: true,
      banner: null,
      colors: ['Orange', 'Black', 'White'],
      sizes: ['Small', 'Medium', 'Large', 'X-Large'],
      discount: 30,
    },

    // TOP SELLING - Homepage Section
    {
    name: 'VERTICAL STRIPED SHIRT',
    slug: 'vertical-striped-shirt',
    category: 'shirt',
    description: 'A classic button-up shirt with elegant vertical stripes. Versatile design that works for both business casual and smart casual occasions.',
    images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
    price: 21200,
      brand: 'Casual',
      rating: 5.0,
      numReviews: 0,
      stock: 45,
      isFeatured: true,
      banner: null,
      colors: ['Blue/White', 'Pink/White', 'Black/White'],
      sizes: ['Small', 'Medium', 'Large', 'X-Large'],
      discount: 20,
    },
    {
    name: 'COURAGE GRAPHIC T-SHIRT',
    slug: 'courage-graphic-t-shirt',
    category: 't-shirts',
    description: 'Express yourself with this bold graphic t-shirt featuring an inspiring courage design. Made from soft cotton for all-day comfort.',
    images: ['/images/sample-products/p6-1.jpg'],
    price: 14500,
      brand: 'Casual',
      rating: 4.0,
      numReviews: 0,
      stock: 80,
      isFeatured: true,
      banner: null,
      colors: ['Black', 'White', 'Navy'],
      sizes: ['Small', 'Medium', 'Large', 'X-Large'],
      discount: 0,
    },
    {
    name: 'LOOSE FIT BERMUDA SHORTS',
    slug: 'loose-fit-bermuda-shorts',
    category: 'shorts',
    description: 'Comfortable bermuda shorts with a relaxed loose fit. Perfect for warm weather with a classic knee-length cut and multiple color options.',
    images: ['/images/sample-products/p7-1.jpg'],
    price: 8000,
      brand: 'Casual',
      rating: 3.0,
      numReviews: 0,
      stock: 120,
      isFeatured: true,
      banner: null,
      colors: ['Khaki', 'Navy', 'Black', 'Olive'],
      sizes: ['Small', 'Medium', 'Large', 'X-Large'],
      discount: 0,
    },
    {
    name: 'FADED SKINNY JEANS',
    slug: 'faded-skinny-jeans',
    category: 'jeans',
    description: 'Trendy skinny jeans with a vintage faded wash. Features a modern slim fit with stretch denim for comfort and style.',
    images: ['/images/sample-products/p8-1.jpg'],
    price: 21000,
      brand: 'Casual',
      rating: 4.5,
      numReviews: 0,
      stock: 60,
      isFeatured: true,
      banner: null,
      colors: ['Light Blue', 'Medium Blue', 'Dark Blue'],
      sizes: ['Small', 'Medium', 'Large', 'X-Large'],
      discount: 0,
    },

    // FEATURED PRODUCT - Product Detail Page
    {
    name: 'One Life Graphic T-shirt',
    slug: 'one-life-graphic-t-shirt',
    category: 't-shirts',
    description: 'Make a statement with this eye-catching graphic t-shirt. Premium quality cotton with a unique design celebrating life and positivity.',
    images: [
      '/images/sample-products/p1-1.jpg',
      '/images/sample-products/p1-2.jpg',
      '/images/sample-products/p2-1.jpg',
    ],
    price: 26000,
      brand: 'Men',
      rating: 4.5,
      numReviews: 451,
      stock: 100,
      isFeatured: true,
      banner: null,
      colors: ['Olive Green', 'Dark Green', 'Navy Blue'],
      sizes: ['Small', 'Medium', 'Large', 'X-Large'],
      discount: 40,
    },

    // YOU MIGHT ALSO LIKE - Product Detail Page
    {
    name: 'Polo with Contrast Trims',
    slug: 'polo-with-contrast-trims',
    category: 'polo',
    description: 'Sophisticated polo shirt with distinctive contrast trims on collar and cuffs. Breathable fabric perfect for both sports and casual wear.',
    images: ['/images/sample-products/p3-1.jpg'],
    price: 21200,
      brand: 'Casual',
      rating: 4.0,
      numReviews: 145,
      stock: 55,
      isFeatured: false,
      banner: null,
      colors: ['Black', 'White', 'Navy'],
      sizes: ['Small', 'Medium', 'Large', 'X-Large'],
      discount: 20,
    },
    {
    name: 'Gradient Graphic T-shirt',
    slug: 'gradient-graphic-t-shirt',
    category: 't-shirts',
    description: 'Stand out with this vibrant gradient graphic t-shirt. Modern design with smooth color transitions and comfortable cotton blend fabric.',
    images: ['/images/sample-products/p4-1.jpg'],
    price: 14500,
      brand: 'Casual',
      rating: 3.5,
      numReviews: 67,
      stock: 100,
      isFeatured: false,
      banner: null,
      colors: ['Orange', 'Blue', 'Purple'],
      sizes: ['Small', 'Medium', 'Large', 'X-Large'],
      discount: 0,
    },
    {
    name: 'Polo with Tipping Details',
    slug: 'polo-with-tipping-details',
    category: 'polo',
    description: 'Classic polo shirt elevated with refined tipping details. Features a timeless design with premium pique cotton fabric for lasting comfort.',
    images: ['/images/sample-products/p5-1.jpg'],
    price: 18000,
      brand: 'Casual',
      rating: 4.5,
      numReviews: 98,
      stock: 70,
      isFeatured: false,
      banner: null,
      colors: ['White', 'Black', 'Navy'],
      sizes: ['Small', 'Medium', 'Large', 'X-Large'],
      discount: 0,
    },
    {
    name: 'Black Striped T-shirt',
    slug: 'black-striped-t-shirt',
    category: 't-shirts',
    description: 'Essential striped t-shirt with a sleek black and neutral color palette. Versatile wardrobe staple that pairs well with any casual outfit.',
    images: ['/images/sample-products/p6-1.jpg'],
    price: 12000,
      brand: 'Casual',
      rating: 5.0,
      numReviews: 312,
      stock: 200,
      isFeatured: false,
      banner: null,
      colors: ['Black', 'White', 'Gray'],
      sizes: ['Small', 'Medium', 'Large', 'X-Large'],
      discount: 30,
    },
  ],

  users: [
    {
      name: 'Admin User',
      email: 'admin@example.com',
      password: hashSync('123456', 10),
      role: 'admin',
    },
    {
      name: 'Samantha D.',
      email: 'samantha.d@example.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
    {
      name: 'Alex M.',
      email: 'alex.m@example.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
    {
      name: 'Ethan R.',
      email: 'ethan.r@example.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
    {
      name: 'Olivia P.',
      email: 'olivia.p@example.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
    {
      name: 'Liam K.',
      email: 'liam.k@example.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
    {
      name: 'Ava H.',
      email: 'ava.h@example.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
    {
      name: 'Sarah M.',
      email: 'sarah.m@example.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
    {
      name: 'Alex K.',
      email: 'alex.k@example.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
    {
      name: 'James L.',
      email: 'james.l@example.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
  ],

  // Reviews specifically for "One Life Graphic T-shirt" product
  productReviews: [
    {
      productSlug: 'one-life-graphic-t-shirt',
      userName: 'Samantha D.',
      rating: 5,
      title: 'Absolutely love it!',
      comment: 'I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. It\'s become my favorite go-to shirt.',
      isVerified: true,
      createdAt: new Date('2023-08-14'),
    },
    {
      productSlug: 'one-life-graphic-t-shirt',
      userName: 'Alex M.',
      rating: 4,
      title: 'Exceeded expectations!',
      comment: 'The t-shirt exceeded my expectations! The colors are vibrant and the print quality is top-notch. Being a UI/UX designer myself, I\'m quite picky about aesthetics, and this t-shirt definitely gets a thumbs up from me.',
      isVerified: true,
      createdAt: new Date('2023-08-15'),
    },
    {
      productSlug: 'one-life-graphic-t-shirt',
      userName: 'Ethan R.',
      rating: 5,
      title: 'Must-have for design lovers',
      comment: 'This t-shirt is a must-have for anyone who appreciates good design. The minimalistic yet stylish pattern caught my eye, and the fit is perfect. I can see the designer\'s touch in every aspect of this shirt.',
      isVerified: true,
      createdAt: new Date('2023-08-16'),
    },
    {
      productSlug: 'one-life-graphic-t-shirt',
      userName: 'Olivia P.',
      rating: 4,
      title: 'Simplicity meets functionality',
      comment: 'As a UI/UX enthusiast, I value simplicity and functionality. This t-shirt not only represents those principles but also feels great to wear. It\'s evident that the designer poured their creativity into making this t-shirt stand out.',
      isVerified: true,
      createdAt: new Date('2023-08-17'),
    },
    {
      productSlug: 'one-life-graphic-t-shirt',
      userName: 'Liam K.',
      rating: 5,
      title: 'Comfort meets creativity',
      comment: 'This t-shirt is a fusion of comfort and creativity. The fabric is soft, and the design speaks volumes about the designer\'s skill. It\'s like wearing a piece of art that reflects my passion for both design and fashion.',
      isVerified: true,
      createdAt: new Date('2023-08-18'),
    },
    {
      productSlug: 'one-life-graphic-t-shirt',
      userName: 'Ava H.',
      rating: 5,
      title: 'Wearing design philosophy',
      comment: 'I\'m not just wearing a t-shirt; I\'m wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter.',
      isVerified: true,
      createdAt: new Date('2023-08-19'),
    },
  ],

  // Generic reviews for other products
  reviews: [
    {
      rating: 5,
      title: 'Excellent quality!',
      comment: 'This product is exactly what I was looking for. Great quality and perfect fit. Would definitely recommend!',
      isVerified: true,
    },
    {
      rating: 4,
      title: 'Good but runs small',
      comment: 'Nice quality product but consider sizing up. I usually wear Medium but Large fits better. Other than that, great purchase.',
      isVerified: true,
    },
    {
      rating: 5,
      title: 'Perfect for everyday wear',
      comment: 'Looks great and feels comfortable all day long. Will definitely buy more.',
      isVerified: true,
    },
    {
      rating: 3,
      title: 'Average product',
      comment: 'It\'s okay for the price. Nothing special but does the job. Material could be better quality.',
      isVerified: false,
    },
    {
      rating: 5,
      title: 'Love it!',
      comment: 'Best purchase I have made in a while. Highly recommend! The fit is perfect and the quality exceeds expectations.',
      isVerified: true,
    },
    {
      rating: 4,
      title: 'Great value for money',
      comment: 'Excellent quality at this price point. Very satisfied with my purchase. The color is exactly as shown in pictures.',
      isVerified: true,
    },
    {
      rating: 5,
      title: 'Super comfortable',
      comment: 'Worn this multiple times already and it still looks brand new. The fabric is soft and breathable.',
      isVerified: true,
    },
    {
      rating: 4,
      title: 'Good purchase',
      comment: 'Happy with this buy. Fits well and looks good. Minor stitching issue but nothing major.',
      isVerified: true,
    },
    {
      rating: 5,
      title: 'Best in class',
      comment: 'After trying several brands, this is by far the best. The attention to detail is impressive.',
      isVerified: true,
    },
    {
      rating: 3,
      title: 'Decent quality',
      comment: 'Not bad, but not exceptional either. For the price it\'s acceptable. Would prefer better packaging.',
      isVerified: false,
    },
  ],

  // Testimonials for homepage
  testimonials: [
    {
      userName: 'Sarah M.',
      rating: 5,
      comment: 'I\'m blown away by the quality and style of the clothes I received from Shop.co. From casual wear to elegant dresses, every piece I\'ve bought has exceeded my expectations.',
      isVerified: true,
    },
    {
      userName: 'Alex K.',
      rating: 5,
      comment: 'Finding clothes that align with my personal style used to be a challenge until I discovered Shop.co. The range of options they offer is truly remarkable, catering to a variety of tastes and occasions.',
      isVerified: true,
    },
    {
      userName: 'James L.',
      rating: 5,
      comment: 'As someone who\'s always on the lookout for unique fashion pieces, I\'m thrilled to have stumbled upon Shop.co. The selection of clothes is not only diverse but also on-point with the latest trends.',
      isVerified: true,
    },
  ],
};

export default figmaSampleData;
