import { hashSync } from 'bcrypt';

const sampleData = {
  products: [
    // Featured Products (existing + enhanced)
    {
      name: 'Polo Sporting Stretch Shirt',
      slug: 'polo-sporting-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Classic Polo style with modern comfort. Made from premium stretch fabric that moves with you throughout the day. Perfect for business casual or smart casual occasions.',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 59.99,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 120,
      stock: 45,
      isFeatured: true,
      banner: '/images/banner-1.jpg',
      colors: ['White', 'Blue', 'Pink'],
      sizes: ['S', 'M', 'L', 'XL'],
      discount: 0,
    },
    {
      name: 'Brooks Brothers Long Sleeved Shirt',
      slug: 'brooks-brothers-long-sleeved-shirt',
      category: "Men's Dress Shirts",
      description: 'Timeless style and premium comfort. This non-iron dress shirt features a traditional fit and our signature quality construction.',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 85.90,
      brand: 'Brooks Brothers',
      rating: 4.2,
      numReviews: 89,
      stock: 30,
      isFeatured: true,
      banner: '/images/banner-2.jpg',
      colors: ['White', 'Blue', 'Gray'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      discount: 10,
    },
    {
      name: 'Tommy Hilfiger Classic Fit Dress Shirt',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'A perfect blend of sophistication and comfort. Features the iconic Tommy Hilfiger flag logo and premium cotton fabric.',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 156,
      stock: 0,
      isFeatured: false,
      banner: null,
      colors: ['White', 'Navy', 'Red'],
      sizes: ['S', 'M', 'L', 'XL'],
      discount: 0,
    },
    {
      name: 'Calvin Klein Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Streamlined design with flexible stretch fabric. Modern slim fit for a contemporary silhouette.',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 78,
      stock: 60,
      isFeatured: false,
      banner: null,
      colors: ['Black', 'White', 'Blue'],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      discount: 20,
    },
    {
      name: 'Polo Ralph Lauren Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'Iconic Polo design with refined oxford fabric. The perfect combination of casual and sophisticated.',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 79.99,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 234,
      stock: 25,
      isFeatured: true,
      banner: null,
      colors: ['Blue', 'White', 'Pink', 'Green'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      discount: 0,
    },
    {
      name: 'Polo Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      category: "Men's Sweatshirts",
      description: 'Soft, stylish, and perfect for laid-back days. Premium cotton blend with the iconic Polo pony embroidery.',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 99.99,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 189,
      stock: 40,
      isFeatured: true,
      banner: null,
      colors: ['Pink', 'Navy', 'Gray', 'Black'],
      sizes: ['S', 'M', 'L', 'XL'],
      discount: 15,
    },
    // T-Shirts
    {
      name: 'Gradient Graphic T-shirt',
      slug: 'gradient-graphic-t-shirt',
      category: "T-shirts",
      description: 'Eye-catching gradient design on premium cotton. Perfect for making a statement.',
      images: [
        'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
        'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500',
      ],
      price: 145.00,
      brand: 'Urban Style',
      rating: 3.5,
      numReviews: 67,
      stock: 100,
      isFeatured: false,
      banner: null,
      colors: ['Orange', 'Blue', 'Purple'],
      sizes: ['S', 'M', 'L', 'XL'],
      discount: 0,
    },
    {
      name: 'Polo With Contrast Trims',
      slug: 'polo-with-contrast-trims',
      category: "T-shirts",
      description: 'Classic polo shirt with modern contrast trim details. Breathable pique cotton fabric.',
      images: [
        'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=500',
        'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=500',
      ],
      price: 212.00,
      brand: 'Polo',
      rating: 4.0,
      numReviews: 145,
      stock: 55,
      isFeatured: false,
      banner: null,
      colors: ['Black', 'White', 'Navy'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      discount: 20,
    },
    {
      name: 'Black Striped T-shirt',
      slug: 'black-striped-t-shirt',
      category: "T-shirts",
      description: 'Timeless striped design in comfortable cotton. Versatile for any casual occasion.',
      images: [
        'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500',
        'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=500',
      ],
      price: 120.00,
      brand: 'Basics',
      rating: 5.0,
      numReviews: 312,
      stock: 200,
      isFeatured: true,
      banner: null,
      colors: ['Black', 'White', 'Gray'],
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      discount: 30,
    },
    {
      name: 'Skinny Fit Jeans',
      slug: 'skinny-fit-jeans',
      category: "Jeans",
      description: 'Modern skinny fit with comfort stretch. The perfect blend of style and flexibility.',
      images: [
        'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500',
        'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500',
      ],
      price: 240.00,
      brand: 'Denim Co',
      rating: 3.5,
      numReviews: 178,
      stock: 75,
      isFeatured: false,
      banner: null,
      colors: ['Blue', 'Black', 'Gray'],
      sizes: ['28', '30', '32', '34', '36'],
      discount: 20,
    },
    {
      name: 'Checkered Shirt',
      slug: 'checkered-shirt',
      category: "Shirts",
      description: 'Classic checkered pattern in soft cotton flannel. Perfect for casual outings.',
      images: [
        'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500',
        'https://images.unsplash.com/photo-1588359348347-9bc6cbbb689e?w=500',
      ],
      price: 180.00,
      brand: 'Country Club',
      rating: 4.5,
      numReviews: 234,
      stock: 90,
      isFeatured: false,
      banner: null,
      colors: ['Red', 'Blue', 'Green'],
      sizes: ['S', 'M', 'L', 'XL'],
      discount: 0,
    },
    {
      name: 'Sleeve Striped T-shirt',
      slug: 'sleeve-striped-t-shirt',
      category: "T-shirts",
      description: 'Unique sleeve stripe design. Stand out with this contemporary take on casual wear.',
      images: [
        'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=500',
        'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500',
      ],
      price: 130.00,
      brand: 'Street Wear',
      rating: 4.5,
      numReviews: 156,
      stock: 120,
      isFeatured: false,
      banner: null,
      colors: ['Orange', 'Black', 'White'],
      sizes: ['S', 'M', 'L', 'XL'],
      discount: 30,
    },
    // Women's Clothing
    {
      name: 'Womens 3-in-1 Snowboard Jacket',
      slug: 'womens-3-in-1-snowboard-jacket',
      category: "Women's Jackets",
      description: 'Versatile 3-in-1 design with detachable fleece liner. Waterproof and breathable for all weather conditions.',
      images: [
        'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500',
        'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500',
      ],
      price: 56.99,
      brand: 'BIYLACLESEN',
      rating: 4.6,
      numReviews: 235,
      stock: 45,
      isFeatured: false,
      banner: null,
      colors: ['Black', 'Navy', 'Red'],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      discount: 0,
    },
    {
      name: 'Faux Leather Moto Biker Jacket',
      slug: 'faux-leather-moto-biker-jacket',
      category: "Women's Jackets",
      description: 'Edgy faux leather with removable hood. Make a bold fashion statement with this moto-inspired jacket.',
      images: [
        'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500',
        'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500',
      ],
      price: 29.95,
      brand: 'Lock and Love',
      rating: 4.2,
      numReviews: 340,
      stock: 80,
      isFeatured: true,
      banner: null,
      colors: ['Black', 'Brown', 'Burgundy'],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      discount: 10,
    },
    {
      name: 'Rain Jacket Women Windbreaker',
      slug: 'rain-jacket-women-windbreaker',
      category: "Women's Jackets",
      description: 'Lightweight and packable rain protection. Features adjustable hood and waist for a customized fit.',
      images: [
        'https://images.unsplash.com/photo-1545594861-3bef43ff2fc8?w=500',
        'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500',
      ],
      price: 39.99,
      brand: 'Outdoor Essential',
      rating: 3.8,
      numReviews: 679,
      stock: 150,
      isFeatured: false,
      banner: null,
      colors: ['Yellow', 'Pink', 'Blue', 'Green'],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      discount: 0,
    },
    {
      name: 'Solid Short Sleeve Boat Neck',
      slug: 'solid-short-sleeve-boat-neck',
      category: "Women's Tops",
      description: 'Elegant boat neck design in soft rayon blend. Perfect for layering or wearing alone.',
      images: [
        'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=500',
        'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=500',
      ],
      price: 9.85,
      brand: 'MBJ',
      rating: 4.7,
      numReviews: 130,
      stock: 200,
      isFeatured: false,
      banner: null,
      colors: ['Black', 'White', 'Navy', 'Red', 'Pink'],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      discount: 0,
    },
    {
      name: 'Short Sleeve Moisture Wicking Tee',
      slug: 'short-sleeve-moisture-wicking-tee',
      category: "Women's Sports",
      description: 'Performance fabric that keeps you cool and dry. Perfect for workouts or active days.',
      images: [
        'https://images.unsplash.com/photo-1518459031867-a89b944bffe4?w=500',
        'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=500',
      ],
      price: 7.95,
      brand: 'Opna',
      rating: 4.5,
      numReviews: 146,
      stock: 180,
      isFeatured: false,
      banner: null,
      colors: ['Black', 'White', 'Pink', 'Purple'],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      discount: 15,
    },
    {
      name: 'Cotton Casual T Shirt',
      slug: 'cotton-casual-t-shirt',
      category: "Women's Tops",
      description: 'Soft cotton with a relaxed fit. Everyday essential with letter print design.',
      images: [
        'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=500',
        'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500',
      ],
      price: 12.99,
      brand: 'DANVOUY',
      rating: 3.6,
      numReviews: 145,
      stock: 250,
      isFeatured: false,
      banner: null,
      colors: ['White', 'Black', 'Gray', 'Pink'],
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      discount: 0,
    },
    // Electronics inspired fashion accessories
    {
      name: 'Premium Leather Backpack',
      slug: 'premium-leather-backpack',
      category: "Accessories",
      description: 'Stylish leather backpack with laptop compartment. Perfect for work or travel with multiple pockets.',
      images: [
        'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500',
        'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500',
      ],
      price: 109.95,
      brand: 'Fjallraven',
      rating: 4.9,
      numReviews: 520,
      stock: 35,
      isFeatured: true,
      banner: null,
      colors: ['Black', 'Brown', 'Navy'],
      sizes: ['One Size'],
      discount: 0,
    },
    {
      name: 'Mens Casual Premium Slim Fit Henley',
      slug: 'mens-casual-premium-slim-fit-henley',
      category: "Men's Tops",
      description: 'Slim-fitting henley with contrast raglan sleeves. Lightweight and breathable for comfortable all-day wear.',
      images: [
        'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=500',
        'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500',
      ],
      price: 22.30,
      brand: 'Premium Basics',
      rating: 4.1,
      numReviews: 259,
      stock: 120,
      isFeatured: false,
      banner: null,
      colors: ['White', 'Black', 'Navy', 'Gray'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      discount: 0,
    },
    {
      name: 'Mens Cotton Jacket',
      slug: 'mens-cotton-jacket',
      category: "Men's Jackets",
      description: 'Versatile cotton jacket for Spring/Autumn/Winter. Great for outdoor activities and casual wear.',
      images: [
        'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500',
        'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500',
      ],
      price: 55.99,
      brand: 'Outdoor Pro',
      rating: 4.7,
      numReviews: 500,
      stock: 65,
      isFeatured: true,
      banner: null,
      colors: ['Black', 'Navy', 'Olive', 'Khaki'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      discount: 25,
    },
    // Jewelry inspired items
    {
      name: 'Gold & Silver Dragon Bracelet',
      slug: 'gold-silver-dragon-bracelet',
      category: "Jewelry",
      description: 'From our Legends Collection, the Naga was inspired by the mythical water dragon. Wear facing inward for love and abundance.',
      images: [
        'https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=500',
        'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=500',
      ],
      price: 695.00,
      brand: 'John Hardy',
      rating: 4.6,
      numReviews: 400,
      stock: 10,
      isFeatured: false,
      banner: null,
      colors: ['Gold/Silver'],
      sizes: ['One Size'],
      discount: 0,
    },
    {
      name: 'Solid Gold Micropave Ring',
      slug: 'solid-gold-micropave-ring',
      category: "Jewelry",
      description: 'Stunning micropave design in solid gold. Perfect for special occasions or everyday elegance.',
      images: [
        'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=500',
        'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=500',
      ],
      price: 168.00,
      brand: 'Hafeez Center',
      rating: 3.9,
      numReviews: 70,
      stock: 15,
      isFeatured: false,
      banner: null,
      colors: ['Gold'],
      sizes: ['5', '6', '7', '8', '9'],
      discount: 10,
    },
    {
      name: 'White Gold Diamond Ring',
      slug: 'white-gold-diamond-ring',
      category: "Jewelry",
      description: 'Classic solitaire diamond promise ring. Perfect for engagements, weddings, or anniversaries.',
      images: [
        'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=500',
        'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=500',
      ],
      price: 9.99,
      brand: 'Promise Jewelry',
      rating: 3.0,
      numReviews: 400,
      stock: 100,
      isFeatured: false,
      banner: null,
      colors: ['White Gold'],
      sizes: ['5', '6', '7', '8', '9'],
      discount: 0,
    },
    {
      name: 'Rose Gold Plated Earrings',
      slug: 'rose-gold-plated-earrings',
      category: "Jewelry",
      description: 'Elegant rose gold plated stainless steel earrings. Hypoallergenic and perfect for sensitive ears.',
      images: [
        'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=500',
        'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=500',
      ],
      price: 10.99,
      brand: 'Pierced Owl',
      rating: 3.9,
      numReviews: 100,
      stock: 200,
      isFeatured: false,
      banner: null,
      colors: ['Rose Gold'],
      sizes: ['One Size'],
      discount: 20,
    },
    // Additional fashion items
    {
      name: 'Vertical Striped Shirt',
      slug: 'vertical-striped-shirt',
      category: "Shirts",
      description: 'Classic vertical stripes in premium cotton. A timeless addition to any wardrobe.',
      images: [
        'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500',
        'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500',
      ],
      price: 212.00,
      brand: 'Executive',
      rating: 5.0,
      numReviews: 289,
      stock: 45,
      isFeatured: false,
      banner: null,
      colors: ['Blue/White', 'Pink/White', 'Black/White'],
      sizes: ['S', 'M', 'L', 'XL'],
      discount: 20,
    },
    {
      name: 'Courage Graphic T-shirt',
      slug: 'courage-graphic-t-shirt',
      category: "T-shirts",
      description: 'Bold graphic design with inspiring message. Made from 100% organic cotton.',
      images: [
        'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=500',
        'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500',
      ],
      price: 145.00,
      brand: 'Inspire Wear',
      rating: 4.0,
      numReviews: 134,
      stock: 80,
      isFeatured: false,
      banner: null,
      colors: ['Black', 'White', 'Navy'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      discount: 0,
    },
    {
      name: 'Loose Fit Bermuda Shorts',
      slug: 'loose-fit-bermuda-shorts',
      category: "Shorts",
      description: 'Comfortable loose fit bermuda shorts. Perfect for summer days and casual outings.',
      images: [
        'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500',
        'https://images.unsplash.com/photo-1565084888279-aca607ecce0c?w=500',
      ],
      price: 80.00,
      brand: 'Summer Style',
      rating: 3.0,
      numReviews: 98,
      stock: 120,
      isFeatured: false,
      banner: null,
      colors: ['Khaki', 'Navy', 'Black', 'Olive'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      discount: 0,
    },
    {
      name: 'Faded Skinny Jeans',
      slug: 'faded-skinny-jeans',
      category: "Jeans",
      description: 'Trendy faded wash skinny jeans. Stretch denim for all-day comfort.',
      images: [
        'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500',
        'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500',
      ],
      price: 210.00,
      brand: 'Denim Co',
      rating: 4.5,
      numReviews: 256,
      stock: 60,
      isFeatured: false,
      banner: null,
      colors: ['Light Blue', 'Medium Blue', 'Dark Blue'],
      sizes: ['28', '30', '32', '34', '36', '38'],
      discount: 15,
    },
    // Hoodies and Sweatshirts
    {
      name: 'Classic Crew Neck Sweatshirt',
      slug: 'classic-crew-neck-sweatshirt',
      category: "Sweatshirts",
      description: 'Cozy fleece-lined crew neck sweatshirt. A wardrobe staple for cooler days.',
      images: [
        'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500',
        'https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=500',
      ],
      price: 75.00,
      brand: 'Comfort Basics',
      rating: 4.3,
      numReviews: 189,
      stock: 100,
      isFeatured: false,
      banner: null,
      colors: ['Gray', 'Navy', 'Black', 'Burgundy'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      discount: 0,
    },
    {
      name: 'Oversized Graphic Hoodie',
      slug: 'oversized-graphic-hoodie',
      category: "Hoodies",
      description: 'Trendy oversized fit with bold graphic print. Super soft cotton blend.',
      images: [
        'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500',
        'https://images.unsplash.com/photo-1509942774463-acf339cf87d5?w=500',
      ],
      price: 120.00,
      brand: 'Street Culture',
      rating: 4.8,
      numReviews: 345,
      stock: 55,
      isFeatured: true,
      banner: null,
      colors: ['Black', 'White', 'Purple', 'Green'],
      sizes: ['S', 'M', 'L', 'XL'],
      discount: 10,
    },
    // Dresses
    {
      name: 'Floral Midi Dress',
      slug: 'floral-midi-dress',
      category: "Dresses",
      description: 'Elegant floral print midi dress. Perfect for brunch, weddings, or special occasions.',
      images: [
        'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500',
        'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500',
      ],
      price: 185.00,
      brand: 'Bloom Fashion',
      rating: 4.6,
      numReviews: 278,
      stock: 40,
      isFeatured: true,
      banner: null,
      colors: ['Floral Blue', 'Floral Pink', 'Floral Yellow'],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      discount: 0,
    },
    {
      name: 'Little Black Dress',
      slug: 'little-black-dress',
      category: "Dresses",
      description: 'The essential LBD. Timeless elegance for any occasion.',
      images: [
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500',
        'https://images.unsplash.com/photo-1550928431-ee0ec6db30d3?w=500',
      ],
      price: 250.00,
      brand: 'Elegance',
      rating: 4.9,
      numReviews: 412,
      stock: 25,
      isFeatured: false,
      banner: null,
      colors: ['Black'],
      sizes: ['XS', 'S', 'M', 'L'],
      discount: 5,
    },
    // Accessories
    {
      name: 'Classic Leather Belt',
      slug: 'classic-leather-belt',
      category: "Accessories",
      description: 'Genuine leather belt with polished buckle. Essential accessory for every wardrobe.',
      images: [
        'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=500',
        'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500',
      ],
      price: 45.00,
      brand: 'Classic Style',
      rating: 4.4,
      numReviews: 156,
      stock: 200,
      isFeatured: false,
      banner: null,
      colors: ['Black', 'Brown', 'Tan'],
      sizes: ['S', 'M', 'L', 'XL'],
      discount: 0,
    },
    {
      name: 'Wool Blend Scarf',
      slug: 'wool-blend-scarf',
      category: "Accessories",
      description: 'Luxuriously soft wool blend scarf. Stay warm in style this winter.',
      images: [
        'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=500',
        'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=500',
      ],
      price: 65.00,
      brand: 'Winter Warmth',
      rating: 4.7,
      numReviews: 89,
      stock: 75,
      isFeatured: false,
      banner: null,
      colors: ['Gray', 'Navy', 'Burgundy', 'Camel'],
      sizes: ['One Size'],
      discount: 15,
    },
    {
      name: 'Canvas Messenger Bag',
      slug: 'canvas-messenger-bag',
      category: "Accessories",
      description: 'Durable canvas messenger bag with leather accents. Perfect for daily commute.',
      images: [
        'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500',
        'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500',
      ],
      price: 89.00,
      brand: 'Urban Carry',
      rating: 4.5,
      numReviews: 234,
      stock: 50,
      isFeatured: false,
      banner: null,
      colors: ['Khaki', 'Gray', 'Black'],
      sizes: ['One Size'],
      discount: 0,
    },
    // Shoes
    {
      name: 'Classic White Sneakers',
      slug: 'classic-white-sneakers',
      category: "Shoes",
      description: 'Timeless white sneakers with premium leather upper. Versatile for any outfit.',
      images: [
        'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500',
        'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=500',
      ],
      price: 135.00,
      brand: 'Step Up',
      rating: 4.8,
      numReviews: 567,
      stock: 80,
      isFeatured: true,
      banner: null,
      colors: ['White', 'White/Black', 'White/Navy'],
      sizes: ['7', '8', '9', '10', '11', '12'],
      discount: 0,
    },
    {
      name: 'Running Performance Shoes',
      slug: 'running-performance-shoes',
      category: "Shoes",
      description: 'High-performance running shoes with responsive cushioning. Built for speed and comfort.',
      images: [
        'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
        'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=500',
      ],
      price: 165.00,
      brand: 'Athletic Pro',
      rating: 4.6,
      numReviews: 423,
      stock: 65,
      isFeatured: false,
      banner: null,
      colors: ['Black/Red', 'Blue/White', 'Gray/Orange'],
      sizes: ['7', '8', '9', '10', '11', '12', '13'],
      discount: 20,
    },
    // Formal wear
    {
      name: 'Slim Fit Blazer',
      slug: 'slim-fit-blazer',
      category: "Formal",
      description: 'Modern slim fit blazer in premium wool blend. Perfect for business or formal events.',
      images: [
        'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500',
        'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=500',
      ],
      price: 299.00,
      brand: 'Executive Style',
      rating: 4.7,
      numReviews: 189,
      stock: 30,
      isFeatured: false,
      banner: null,
      colors: ['Navy', 'Charcoal', 'Black'],
      sizes: ['S', 'M', 'L', 'XL'],
      discount: 0,
    },
    {
      name: 'Tailored Dress Pants',
      slug: 'tailored-dress-pants',
      category: "Formal",
      description: 'Classic tailored dress pants with comfort stretch. Essential for any professional wardrobe.',
      images: [
        'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500',
        'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500',
      ],
      price: 125.00,
      brand: 'Executive Style',
      rating: 4.4,
      numReviews: 156,
      stock: 70,
      isFeatured: false,
      banner: null,
      colors: ['Black', 'Navy', 'Charcoal', 'Khaki'],
      sizes: ['30', '32', '34', '36', '38'],
      discount: 10,
    },
  ],
  users: [
    {
      name: 'Admin User',
      email: 'admin@example.com',
      password: hashSync('123456', 10),
      role: 'admin',
    },
    {
      name: 'Jane Doe',
      email: 'user@example.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
    {
      name: 'John Smith',
      email: 'john@example.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
    {
      name: 'Sarah Wilson',
      email: 'sarah@example.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
  ],
  reviews: [
    {
      rating: 5,
      title: 'Excellent quality!',
      comment: 'This shirt is exactly what I was looking for. Great fabric and perfect fit.',
      isVerified: true,
    },
    {
      rating: 4,
      title: 'Good but runs small',
      comment: 'Nice quality shirt but consider sizing up. I usually wear L but XL fits better.',
      isVerified: true,
    },
    {
      rating: 5,
      title: 'Perfect for work',
      comment: 'Looks professional and feels comfortable. Will definitely buy more colors.',
      isVerified: true,
    },
    {
      rating: 3,
      title: 'Average product',
      comment: 'Its okay for the price. Nothing special but does the job.',
      isVerified: false,
    },
    {
      rating: 5,
      title: 'Love it!',
      comment: 'Best purchase I have made in a while. Highly recommend!',
      isVerified: true,
    },
  ],
};

export default sampleData;
